
export interface CryptoCompany {
  id: string;
  name: string;
  symbol: string;
  logoUrl: string;
  price: number;
  marketCap: number;
  volume24h: number;
  change24h: number;
  change7d?: number;
  description?: string;
  websiteUrl?: string;
  founded?: string;
  headquarters?: string;
}

export const cryptoCompanies: CryptoCompany[] = [
  {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    logoUrl: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
    price: 62475.32,
    marketCap: 1219673541235,
    volume24h: 28754123567,
    change24h: 2.45,
    change7d: 5.67,
    description: "The original cryptocurrency that started it all, Bitcoin is a peer-to-peer electronic cash system.",
    websiteUrl: "https://bitcoin.org",
    founded: "2009",
    headquarters: "Decentralized"
  },
  {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    logoUrl: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
    price: 3452.18,
    marketCap: 415267834512,
    volume24h: 18453627485,
    change24h: 3.21,
    change7d: 6.32,
    description: "A decentralized platform that runs smart contracts, enabling developers to build decentralized applications (dApps).",
    websiteUrl: "https://ethereum.org",
    founded: "2015",
    headquarters: "Decentralized"
  },
  {
    id: "binance-coin",
    name: "Binance Coin",
    symbol: "BNB",
    logoUrl: "https://cryptologos.cc/logos/bnb-bnb-logo.png",
    price: 591.47,
    marketCap: 91245367821,
    volume24h: 2345678901,
    change24h: -1.23,
    change7d: 4.56,
    description: "Native cryptocurrency of the Binance ecosystem, used for trading fee discounts and more.",
    websiteUrl: "https://binance.com",
    founded: "2017",
    headquarters: "Malta"
  },
  {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    logoUrl: "https://cryptologos.cc/logos/solana-sol-logo.png",
    price: 143.76,
    marketCap: 63457821345,
    volume24h: 4521367845,
    change24h: 5.67,
    change7d: 12.34,
    description: "A high-performance blockchain supporting smart contracts and decentralized applications.",
    websiteUrl: "https://solana.com",
    founded: "2020",
    headquarters: "San Francisco, CA"
  },
  {
    id: "cardano",
    name: "Cardano",
    symbol: "ADA",
    logoUrl: "https://cryptologos.cc/logos/cardano-ada-logo.png",
    price: 0.57,
    marketCap: 20123456789,
    volume24h: 1234567890,
    change24h: -0.85,
    change7d: -2.45,
    description: "A proof-of-stake blockchain platform that aims to provide a more secure and sustainable ecosystem for decentralized applications.",
    websiteUrl: "https://cardano.org",
    founded: "2017",
    headquarters: "Zug, Switzerland"
  },
  {
    id: "polkadot",
    name: "Polkadot",
    symbol: "DOT",
    logoUrl: "https://cryptologos.cc/logos/polkadot-new-dot-logo.png",
    price: 7.83,
    marketCap: 10987654321,
    volume24h: 987654321,
    change24h: 1.23,
    change7d: 3.45,
    description: "A multi-chain network that enables different blockchains to transfer messages and value in a trust-free fashion.",
    websiteUrl: "https://polkadot.network",
    founded: "2016",
    headquarters: "Zug, Switzerland"
  },
  {
    id: "dogecoin",
    name: "Dogecoin",
    symbol: "DOGE",
    logoUrl: "https://cryptologos.cc/logos/dogecoin-doge-logo.png",
    price: 0.12,
    marketCap: 15975346278,
    volume24h: 1357924680,
    change24h: 7.89,
    change7d: 15.67,
    description: "Originally created as a joke currency, Dogecoin has gained popularity and a strong community.",
    websiteUrl: "https://dogecoin.com",
    founded: "2013",
    headquarters: "Decentralized"
  },
  {
    id: "ripple",
    name: "Ripple",
    symbol: "XRP",
    logoUrl: "https://cryptologos.cc/logos/xrp-xrp-logo.png",
    price: 0.58,
    marketCap: 29876543210,
    volume24h: 2468135790,
    change24h: -2.34,
    change7d: -5.67,
    description: "A real-time gross settlement system, currency exchange and remittance network created by Ripple Labs.",
    websiteUrl: "https://ripple.com",
    founded: "2012",
    headquarters: "San Francisco, CA"
  },
  {
    id: "chainlink",
    name: "Chainlink",
    symbol: "LINK",
    logoUrl: "https://cryptologos.cc/logos/chainlink-link-logo.png",
    price: 13.42,
    marketCap: 8765432109,
    volume24h: 654321098,
    change24h: 4.56,
    change7d: 8.90,
    description: "A decentralized oracle network that provides real-world data to smart contracts on the blockchain.",
    websiteUrl: "https://chain.link",
    founded: "2017",
    headquarters: "San Francisco, CA"
  },
  {
    id: "avalanche",
    name: "Avalanche",
    symbol: "AVAX",
    logoUrl: "https://cryptologos.cc/logos/avalanche-avax-logo.png",
    price: 34.21,
    marketCap: 12345678901,
    volume24h: 876543210,
    change24h: 6.78,
    change7d: 9.87,
    description: "A platform for decentralized applications and custom blockchain networks, focusing on speed and low costs.",
    websiteUrl: "https://avax.network",
    founded: "2020",
    headquarters: "Singapore"
  },
  {
    id: "polygon",
    name: "Polygon",
    symbol: "MATIC",
    logoUrl: "https://cryptologos.cc/logos/polygon-matic-logo.png",
    price: 0.87,
    marketCap: 9876543210,
    volume24h: 765432109,
    change24h: 3.45,
    change7d: 7.65,
    description: "A protocol and framework for building and connecting Ethereum-compatible blockchain networks.",
    websiteUrl: "https://polygon.technology",
    founded: "2017",
    headquarters: "Mumbai, India"
  },
  {
    id: "uniswap",
    name: "Uniswap",
    symbol: "UNI",
    logoUrl: "https://cryptologos.cc/logos/uniswap-uni-logo.png",
    price: 7.65,
    marketCap: 7654321098,
    volume24h: 543210987,
    change24h: -1.23,
    change7d: 2.34,
    description: "A decentralized exchange protocol built on Ethereum that uses liquidity pools instead of order books.",
    websiteUrl: "https://uniswap.org",
    founded: "2018",
    headquarters: "Decentralized"
  },
  {
    id: "cosmos",
    name: "Cosmos",
    symbol: "ATOM",
    logoUrl: "https://cryptologos.cc/logos/cosmos-atom-logo.png",
    price: 8.92,
    marketCap: 6543210987,
    volume24h: 432109876,
    change24h: 2.34,
    change7d: 5.67,
    description: "An ecosystem of blockchains that can scale and interoperate with each other.",
    websiteUrl: "https://cosmos.network",
    founded: "2016",
    headquarters: "Berkeley, CA"
  },
  {
    id: "stellar",
    name: "Stellar",
    symbol: "XLM",
    logoUrl: "https://cryptologos.cc/logos/stellar-xlm-logo.png",
    price: 0.11,
    marketCap: 5432109876,
    volume24h: 321098765,
    change24h: 1.23,
    change7d: 3.45,
    description: "An open network for storing and moving money that makes it possible to create, send, and trade digital representations of all forms of money.",
    websiteUrl: "https://stellar.org",
    founded: "2014",
    headquarters: "San Francisco, CA"
  },
  {
    id: "filecoin",
    name: "Filecoin",
    symbol: "FIL",
    logoUrl: "https://cryptologos.cc/logos/filecoin-fil-logo.png",
    price: 5.43,
    marketCap: 4321098765,
    volume24h: 210987654,
    change24h: -3.45,
    change7d: -6.78,
    description: "A decentralized storage network designed to store humanity's most important information.",
    websiteUrl: "https://filecoin.io",
    founded: "2017",
    headquarters: "San Francisco, CA"
  },
  {
    id: "tezos",
    name: "Tezos",
    symbol: "XTZ",
    logoUrl: "https://cryptologos.cc/logos/tezos-xtz-logo.png",
    price: 0.98,
    marketCap: 3210987654,
    volume24h: 109876543,
    change24h: 4.56,
    change7d: 7.89,
    description: "A self-amending blockchain network that incorporates a formal process for protocol upgrades.",
    websiteUrl: "https://tezos.com",
    founded: "2017",
    headquarters: "Zug, Switzerland"
  },
  {
    id: "internet-computer",
    name: "Internet Computer",
    symbol: "ICP",
    logoUrl: "https://cryptologos.cc/logos/internet-computer-icp-logo.png",
    price: 11.23,
    marketCap: 2109876543,
    volume24h: 98765432,
    change24h: 5.67,
    change7d: 9.01,
    description: "A blockchain network that aims to expand the internet's functionality by allowing developers to build and deploy decentralized apps directly on the blockchain.",
    websiteUrl: "https://dfinity.org",
    founded: "2016",
    headquarters: "Zurich, Switzerland"
  },
  {
    id: "aave",
    name: "Aave",
    symbol: "AAVE",
    logoUrl: "https://cryptologos.cc/logos/aave-aave-logo.png",
    price: 92.34,
    marketCap: 1432109876,
    volume24h: 87654321,
    change24h: -2.34,
    change7d: 4.56,
    description: "A decentralized finance protocol that allows people to lend and borrow cryptocurrencies without going through a centralized intermediary.",
    websiteUrl: "https://aave.com",
    founded: "2017",
    headquarters: "London, UK"
  },
  {
    id: "monero",
    name: "Monero",
    symbol: "XMR",
    logoUrl: "https://cryptologos.cc/logos/monero-xmr-logo.png",
    price: 167.89,
    marketCap: 3050789621,
    volume24h: 76543210,
    change24h: 1.23,
    change7d: 2.34,
    description: "A privacy-focused cryptocurrency that uses cryptography to shield sending and receiving addresses, as well as transacted amounts.",
    websiteUrl: "https://getmonero.org",
    founded: "2014",
    headquarters: "Decentralized"
  },
  {
    id: "the-graph",
    name: "The Graph",
    symbol: "GRT",
    logoUrl: "https://cryptologos.cc/logos/the-graph-grt-logo.png",
    price: 0.15,
    marketCap: 1098765432,
    volume24h: 65432109,
    change24h: 3.45,
    change7d: 6.78,
    description: "An indexing protocol for querying networks like Ethereum and IPFS, enabling the creation of decentralized applications.",
    websiteUrl: "https://thegraph.com",
    founded: "2018",
    headquarters: "San Francisco, CA"
  }
];
